// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSAfaIlmELeLsyNBsVAZzW8PDfIHPJ00Q',
    appId: '1:514869363467:web:48eaad0a8a04b3a86cd80e',
    messagingSenderId: '514869363467',
    projectId: 'mytaskaws',
    authDomain: 'mytaskaws.firebaseapp.com',
    storageBucket: 'mytaskaws.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu86bbww-ZujCuYc898rogsCuG9CWwaJ8',
    appId: '1:514869363467:android:2a52c34dff93614b6cd80e',
    messagingSenderId: '514869363467',
    projectId: 'mytaskaws',
    storageBucket: 'mytaskaws.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYf3taYfZU_FD4MQXpJ_jfg3zku1PpWOk',
    appId: '1:514869363467:ios:afc1e55c07f56d3f6cd80e',
    messagingSenderId: '514869363467',
    projectId: 'mytaskaws',
    storageBucket: 'mytaskaws.appspot.com',
    iosClientId: '514869363467-jmlvifjm1bni1iaejpiltka7d4e38ka9.apps.googleusercontent.com',
    iosBundleId: 'com.example.awsbasimtask',
  );
}
